name: update-readme

on:
  schedule:
    - cron: "35 3 * * *"   

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: "3.10"
    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: execute app
      run: |
        python app
      
    - name: commit
      run: |-
        git config pull.rebase false
        git pull
        git add .
        git config --global user.email youremail   
        git config --global user.name yourusername
        git add -A
        git commit -m "[Automated] Update README.md - Add new playlist and update days of the experience" || exit 0
      
    - name: push 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_TOKEN }}