name: update-readme

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 1 * * *"   

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.10" ]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
    - name: execute app
      env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          GROUP_ID: ${{ secrets.GROUP_ID }}
          USER_ID: ${{ secrets.USER_ID }}
      run: |
        export ACCESS_TOKEN="$ACCESS_TOKEN"
        export GROUP_ID="$GROUP_ID"
        export USER_ID="$USER_ID"
        python app
      
    - name: commit
      run: |-
        git config pull.rebase false
        git pull
        git add .
        git config --global user.email github-actions-email   
        git config --global user.name github-actions
        git add -A
        git commit -m "automated: Update README.md - Add new playlist and update days of the experience" || exit 0
      
    - name: push 
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_TOKEN }}